# Generated by Django 5.0.7 on 2024-07-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(db_column='Gender', default=None, max_length=35),
        ),
    ]
